FROM ultralytics/yolov5

# ARG DEBIAN_FRONTEND=noninteractive
# RUN apt-get update -y

# # Works, but without Gstreamer
# RUN apt-get install ffmpeg libsm6 libxext6 -y
# RUN apt-get install -y libsm6 libxext6 libxrender-dev
# RUN pip install opencv-python==4.5.5.64

# RUN pip install scikit-image pycuda
WORKDIR /workspace
EXPOSE 3001